In [1]:
# importing the pandas library
import pandas as pd

In [3]:
#read the index file
index = pd.read_csv(r'Downloads\index.csv')

In [7]:
#Access the third column of the index dataframe
index.iloc[:,2]

0       8
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16     10
17      0
18      0
19      0
20      0
21     55
22      0
23     70
24      3
25      0
26      0
27      0
28     55
29      0
       ..
227     0
228     0
229     0
230     0
231     0
232     0
233     0
234     0
235     0
236    65
237     0
238     0
239     0
240     0
241     0
242     0
243     0
244     0
245     0
246     0
247     0
248     0
249     0
250     0
251     0
252     0
253     6
254     0
255    45
256     6
Name: C, Length: 257, dtype: int64

In [5]:
index

     A  B   C   D  E    F      G      H       I     J    K  L
0    C  A   8   0  S    0   COIL  0.700   610.0     0    0  3
1    C  R   0   0  S    0   COIL  3.200   610.0     0    0  3
2    C  R   0   0  S    0  SHEET  0.700  1300.0   762    0  3
3    C  A   0  60  ?    0   COIL  2.801   385.1     0    0  3
4    C  A   0  60  ?    0  SHEET  0.801   255.0   269    0  3
5    C  A   0  45  S    0   COIL  1.600   610.0     0    0  3
6    C  R   0   0  S    0  SHEET  0.699   610.0  4880    0  3
7    C  A   0   0  S    0   COIL  3.300   152.0     0    0  3
8    C  R   0   0  S    0   COIL  0.699  1320.0     0    0  3
9    C  A   0   0  S    0  SHEET  1.000  1320.0   762    0  3
10   C  R   0   0  S    0   COIL  1.200   610.0     0    0  3
11   C  R   0   0  S    0  SHEET  0.300  1320.0  4880    0  3
12   C  R   0   0  S    0  SHEET  1.200   610.0   150    0  3
13   C  A   0  45  S    0   COIL  1.200   609.9     0    0  3
14   C  A   0   0  S    0  SHEET  0.600  1220.0   761    0  3
15   C  A   0   0  S    0  SHEET  4.000  1320.0   762    0  3
16   C  A  10   0  ?    0   COIL  3.201   600.0     0    0  U
17   C  A   0  80  ?    0  SHEET  0.800   610.0  4170    0  U
18   C  A   0   0  S    0  SHEET  3.200  1320.1   762    0  3
19   C  A   0  70  ?    0   COIL  0.501  1200.1     0    0  3
20   C  A   0   0  S    0  SHEET  0.600   610.0   761    0  3
21   C  K  55   0  ?    0   COIL  0.800   610.0     0    0  3
22   C  A   0  85  ?    0   COIL  1.001    50.0     0    0  U
23   C  S  70   0  ?    0   COIL  3.200   609.9     0    0  3
24   C  A   3   0  ?    0   COIL  0.500   610.0     0    0  1
25   C  ?   0  50  ?    0   COIL  3.200  1320.0     0    0  3
26   C  A   0  60  ?    0  SHEET  0.800   356.0  4880    0  3
27   C  R   0   0  S    0  SHEET  0.700   609.9  4170    0  3
28   C  K  55   0  ?    0   COIL  0.800   900.0     0    0  3
29   C  W   0   0  ?  310   COIL  1.600   610.0     0  500  3
..  .. ..  ..  .. ..  ...    ...    ...     ...   ...  ... ..
227  C  R   0   0  S    0  SHEET  1.599   610.0   761    0  2
228  C  A   0   0  S    0   COIL  0.699   610.0     0    0  3
229  C  R   0   0  S    0   COIL  0.700  1220.0     0    0  3
230  C  R   0   0  S    0   COIL  0.699  1320.0     0    0  3
231  C  A   0  45  S    0  SHEET  0.599   610.0   761    0  3
232  C  A   0   0  S    0  SHEET  0.699   610.0   400    0  3
233  C  A   0  45  S    0  SHEET  1.600  1320.0   612    0  3
234  C  ?   0   0  A    0  SHEET  0.500   609.9   612    0  5
235  C  A   0  45  S    0   COIL  0.301  1320.0     0    0  3
236  C  K  65   0  ?    0   COIL  3.200   640.0     0  500  3
237  C  A   0   0  S    0  SHEET  0.600   610.0   762    0  3
238  C  A   0   0  ?    0   COIL  0.600   249.9     0    0  5
239  C  R   0   0  S    0   COIL  0.700   610.0     0    0  3
240  C  R   0   0  S    0  SHEET  3.200  1300.0   762    0  3
241  C  A   0   0  S    0  SHEET  1.599  1320.0   762    0  3
242  C  A   0   0  S    0   COIL  0.800   609.9     0    0  3
243  C  A   0  60  ?    0   COIL  1.900  1135.0     0  600  3
244  C  V   0   0  S    0   COIL  0.699   609.9     0    0  3
245  C  A   0   0  S    0   COIL  0.699   610.0     0    0  3
246  C  R   0   0  S    0  SHEET  0.800  1320.0   762    0  2
247  C  R   0   0  S    0   COIL  0.901   966.0     0    0  3
248  C  A   0   0  S    0  SHEET  0.700   610.0   762    0  3
249  C  A   0   0  S    0   COIL  0.800    75.0     0    0  3
250  C  R   0   0  S    0  SHEET  0.700  1320.0   762    0  3
251  C  A   0  50  ?    0  SHEET  0.601  1250.0   762    0  3
252  C  A   0  60  ?    0   COIL  0.799   609.0     0    0  3
253  C  R   6   0  ?    0  SHEET  1.000   610.0  4880    0  3
254  C  A   0  50  ?    0   COIL  0.600    20.0     0    0  3
255  C  K  45   0  ?    0   COIL  0.600   900.0     0    0  3
256  C  R   6   0  ?    0  SHEET  1.000   610.0   762    0  3

[257 rows x 12 columns]

In [8]:
index['C']

0       8
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16     10
17      0
18      0
19      0
20      0
21     55
22      0
23     70
24      3
25      0
26      0
27      0
28     55
29      0
       ..
227     0
228     0
229     0
230     0
231     0
232     0
233     0
234     0
235     0
236    65
237     0
238     0
239     0
240     0
241     0
242     0
243     0
244     0
245     0
246     0
247     0
248     0
249     0
250     0
251     0
252     0
253     6
254     0
255    45
256     6
Name: C, Length: 257, dtype: int64

In [12]:
#Access the last two columns of the index df using the iloc function
index.iloc[:,-2:]

       K  L
0      0  3
1      0  3
2      0  3
3      0  3
4      0  3
5      0  3
6      0  3
7      0  3
8      0  3
9      0  3
10     0  3
11     0  3
12     0  3
13     0  3
14     0  3
15     0  3
16     0  U
17     0  U
18     0  3
19     0  3
20     0  3
21     0  3
22     0  U
23     0  3
24     0  1
25     0  3
26     0  3
27     0  3
28     0  3
29   500  3
..   ... ..
227    0  2
228    0  3
229    0  3
230    0  3
231    0  3
232    0  3
233    0  3
234    0  5
235    0  3
236  500  3
237    0  3
238    0  5
239    0  3
240    0  3
241    0  3
242    0  3
243  600  3
244    0  3
245    0  3
246    0  2
247    0  3
248    0  3
249    0  3
250    0  3
251    0  3
252    0  3
253    0  3
254    0  3
255    0  3
256    0  3

[257 rows x 2 columns]

In [13]:
#Access the last ten rows and first two columns of the index df
index.iloc[-10:,:2]

     A  B
247  C  R
248  C  A
249  C  A
250  C  R
251  C  A
252  C  A
253  C  R
254  C  A
255  C  K
256  C  R